### ISSUE TITLE
sendFile regression in Android API level 30

### ISSUE THREAD

**Issue by timsee** [ekke/ekkesSHAREexample#10]
Hello! First off, thanks so much for this project, I've found it quite helpful through the years!

I recently ported code based off of the original blog post to Qt6 in an [application](https://github.com/timsee/Corluma/commit/12c1a1e263566c973f886fe0ac97d158bd95bd4e) I'm working on. For the most part, the port was fairly straightforward, except when I upgraded to android API level 30 (similar to what was done [here](https://github.com/ekke/ekkesSHAREexample/commit/1e2a1d08e34da6c50394c87d62b576cb15d4aa91)) I noticed specifically on Android that the `viewFile` and `share` (for text) operations worked fine, but the `sendFile` no longer worked as it did originally. Instead it requested I open up bluetooth, and then it opened up a bluetooth share screen. I checked out the recent commit here and this sample app has the same behavior:

![Screenshot_20220612-132907](https://user-images.githubusercontent.com/1812471/173246132-aff33d8c-6dcc-4dc2-90a9-08aac9d6c01a.png)
![Screenshot_20220612-132859](https://user-images.githubusercontent.com/1812471/173246133-60b7929b-08f6-41a0-aac4-b7306fbc3df0.png)

**Impacted Devices:**
- Pixel 6 running Android 12
- Moto G Pure running Android 11

**Potential Fix:**
I managed to fix it in my application by simplifying the `sendFile` to no longer use `createCustomChooserAndStartActivity`, but I am not sure if that fix works for all of your use cases:
```
        // create an intent
        Intent intent = new Intent(Intent.ACTION_SEND);
        // add intent save data
        intent.putExtra(Intent.EXTRA_STREAM, uri);
        // set mime type and permissions
        intent.setType(mimeType);
        intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        // send intent
        QtNative.activity().startActivity(Intent.createChooser(intent, null));
```
(see [here](https://github.com/timsee/Corluma/blob/master/src/android/src/org/cor/corluma/utils/QShareUtils.java#L119-L144) for the complete function.)

I'd recommend a similar fix for this sample code, so that no one else ends up going down the same rabbit hole I did! 

Thanks again!

**Comment by ekke** [comment]
Hi,
Thx for your infos. 
In August I’ll start porting my apps to qt6. 
Will take some months. Many apps. Customer apps. Free apps like this one. 
Ciao
ekke (just on vacation)

**Comment by dorianim** [comment]
Thanks for mentioning your solution @timsee! I was facing the exact same issue, and it worked for me too (see [here](https://itsblue.dev/bluerock/app/commit/447c1135dd3629646b08ea1e84b217f39d56aedb)).

**Comment by MisterPascal** [comment]
Hi, I have the same problem for API > 29 when I want to view a .xlsx file. The solution from @dorianim let me now view .xlsx files with API level > 29 again. Thank you!

**Comment by ekke** [comment]
thx @timsee @dorianim ...tried your solution, but it doesn't work on Android 13 devices.
found a better solution in Qt Forum: https://forum.qt.io/topic/127170/android-11-qdir-mkdir-does-not-always-work/10
now for me it works. have updated src. hopefully helps you
thx again to all and sorry that I didn't found more time to work on this. but next 6-9 months I'll transform all projects to Qt6.5 and also rework exmples.
