### ISSUE TITLE
Random behavoiur while accepting content from other applications because of uninitialized class member

### ISSUE THREAD

**Issue by mneuroth** [ekke/ekkesSHAREexample#3]
Thank you for your excellent work! It helped me a lot to improve the Android integration of my (Widget) Qt Apps. While integrating the code of your demo project into one of my projects I found a problem when my Qt Widget Application should accept content from another Android applications. On some devices it worked for some hours on other devices the same APK did not work at all. After some debugging I think that I found the problem:

The bool member mPendingIntentsChecked in the class ApplicationUI is not initialized in the constructor and therefore its value is undefined when used in the method void ApplicationUI::onApplicationStateChanged(). The behaviour of the test of the if statement is somehow random:
 
>    if(!mPendingIntentsChecked) {
>            mPendingIntentsChecked = true;
>            mShareUtils->checkPendingIntents(mAppDataFilesPath);
>    }

Maybe you can add the initial value in the constructor:

> ApplicationUI::ApplicationUI(QObject *parent) : QObject(parent), mShareUtils(new  ShareUtils(this)), mPendingIntentsChecked(false) 
>{
>    ...
>}    

After patching my code with this small fix, my application could reproducible accept content from other android applications.

**Comment by ekke** [comment]
@mneuroth thx mentioning this. makes sense to change that, so I'll change my code.
got no issues yet from my customers - and one app is used by 3,000 employees of an enterprise.
but probably because it's random it's not easy to find.
on the other side: perhaps the timing is different between Widget and QQC2 app.

**Comment by ekke** [comment]
@mneuroth ...long time ago. finally I have initialized the bool ;-)
THX
