### ISSUE TITLE
can i make this project to 'example.pro + qtshareutils.pri' ??

### ISSUE THREAD

**Issue by isdsi** [ekke/ekkesSHAREexample#5]
i try to apply this example to my project.
It is good fuction but, it is not modulated.
I want to make this to get modular.

how about..?

**Comment by ekke** [comment]
this project is only an example project I used to learn HowTo share on Android and iOS and developed in my rare spare time.
I have no time yet to make this modular - I also have no experiences with Qt / QML plugins or so.
feel free to fork the project and do it by yourself

**Comment by isdsi** [comment]
thanks, ekke.

i have forked it. and i changed something, tested on android/ios.

https://github.com/isdsi/ekkesSHAREexample
