### ISSUE TITLE
Sharing problem on android when running in background

### ISSUE THREAD

**Issue by dorianim** [ekke/ekkesSHAREexample#8]
Hi @ekke 
First, thanks for your work, it helped me a lot :D 
I have a strange problem on Android though, where the app freezes in this view:
![image](https://user-images.githubusercontent.com/30153207/122680585-3830a380-d1f0-11eb-914c-98d56c24baeb.png)
Whenever I share a file and the App is already running. Everything works fine again, when I close the app.
I am running on Android 10 using Qt 5.15.2.

**Comment by ekke** [comment]
I'm just in the progress to move my projects from 5.13.2 to 5.15
will take a week or so to finish
then I'll take a look at your problem

**Comment by ekke** [comment]
have done my housework and updated app for Qt 5.15
--
opened app
send in background
goto photos, share a photo and my app comes displaying the photo
tested on Android 9 device, Android 10 device, Qt 5.15.5, QtC 5.14.1

**Comment by dorianim** [comment]
Cool, I'll test it later this week :D

**Comment by dorianim** [comment]
Cool, I'll test it later this week :D

**Comment by dorianim** [comment]
Ok, I tested it, and was able to solve the issue :D
The problem was that I used `android:launchMode="singleTop"`(probably the default)  instead of `android:launchMode="singleInstance"`
over here: https://github.com/ekke/ekkesSHAREexample/blob/4c0aedbad9fe92958bc0ea1b88effd2f2bf5e4ca/android/AndroidManifest.xml#L13

Thank you very much!
