### ISSUE TITLE
Pass onActivityResult to super

### ISSUE THREAD

**Issue by dorianim** [ekke/ekkesSHAREexample#9]
The onActivityResult should be passed to the super class, as it otherwise breaks things like QPurchasing. It can be done by adding   `super.onActivityResult(requestCode, resultCode, data);`  
over here: https://github.com/ekke/ekkesSHAREexample/blob/4c0aedbad9fe92958bc0ea1b88effd2f2bf5e4ca/android/src/org/ekkescorner/examples/sharex/QShareActivity.java#L97

**Comment by ekke** [comment]
thx for the hint - will fix it.

**Comment by emericg** [comment]
I second this fix, thanks @dorianim !

**Comment by ekke** [comment]
@dorianim finally fixed ;-)
THX again
